### ISSUE TITLE
Add RentPaths eslint config

### ISSUE THREAD

**Issue by Teapane** [rentpath/identity.js#19]
https://github.com/rentpath/eslint-config-rentpath

**Comment by martinstreicher** [comment]
@Teapane So `npm run lint` should produce output according to this standard?

**Comment by martinstreicher** [comment]
I have added this to package.json. Can we try it?

**Comment by Teapane** [comment]
Yeah, `npm run lint <file>`

**Comment by martinstreicher** [comment]
This is complete.
